version: '3'
services:

  ai_flask:
    container_name: ai_flask
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn app:app --bind 0.0.0.0:5000 --debug
    ports:
      - "5000:5000"